# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "examples/ruby"
version = "0.0.1"
name = "Ruby Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"
